// Seed additional certification courses — run with: bun run prisma/seed-courses-advanced.ts
import { PrismaClient } from "@prisma/client"

const db = new PrismaClient()

async function main() {
  console.log("Seeding advanced certification courses...")

  // Find an instructor to assign these courses to
  const instructor = await db.user.findFirst({ where: { role: "INSTRUCTOR" } })
  if (!instructor) {
    console.log("No instructor found. Creating one...")
    const bcrypt = await import("bcryptjs")
    const newInstructor = await db.user.create({
      data: {
        email: "instructor2@guardianx.io",
        name: "Dr. Marcus Reeves",
        passwordHash: bcrypt.hashSync("instructor123", 10),
        role: "INSTRUCTOR",
        title: "Senior Security Architect, OSCP/CISSP",
        bio: "20+ years in offensive security, former NSA red team lead.",
      },
    })
    await seedCourses(newInstructor.id)
  } else {
    await seedCourses(instructor.id)
  }

  console.log("Done.")
}

async function seedCourses(instructorId: string) {
  const courses = [
    // --- Offensive Security Track ---
    {
      slug: "oscp-prep",
      title: "OSCP Preparation — Offensive Security Certified Professional",
      shortName: "OSCP",
      description: "Master the art of penetration testing with the industry's most hands-on certification. 24-hour exam, real-world exploits.",
      longDescription: "The OSCP is the gold standard for penetration testing certifications. This course prepares you for the rigorous 24-hour practical exam where you must compromise multiple machines and write a professional report. Covers enumeration, exploitation, privilege escalation, and post-exploitation.",
      category: "Penetration Testing",
      level: "Advanced",
      durationHours: 120,
      price: 0,
      rating: 4.9,
      studentsCount: 3420,
      color: "violet",
      tags: "pentesting,exploitation,privilege-escalation,buffer-overflow",
      certBody: "Offensive Security",
      instructorId,
    },
    {
      slug: "osep-prep",
      title: "OSEP — Offensive Security Experienced Penetration Tester",
      shortName: "OSEP",
      description: "Advanced penetration testing against enterprise environments. Evasion, lateral movement, and Active Directory exploitation.",
      longDescription: "The OSEP certification dives deep into advanced penetration testing techniques including AV/EDR evasion, Active Directory exploitation, lateral movement, and complex network pivoting scenarios.",
      category: "Penetration Testing",
      level: "Advanced",
      durationHours: 90,
      price: 0,
      rating: 4.8,
      studentsCount: 890,
      color: "violet",
      tags: "active-directory,evasion,lateral-movement,advanced",
      certBody: "Offensive Security",
      instructorId,
    },
    {
      slug: "crto-prep",
      title: "CRTO — Certified Red Team Operator",
      shortName: "CRTO",
      description: "Red team operations against mature enterprise environments. Bypassing modern defenses and executing complex attack chains.",
      longDescription: "The CRTO certification focuses on red teaming against organizations with mature security operations. Covers C2 frameworks, defense evasion, and operating in environments with EDR, AV, and SOC teams.",
      category: "Penetration Testing",
      level: "Advanced",
      durationHours: 80,
      price: 0,
      rating: 4.7,
      studentsCount: 560,
      color: "violet",
      tags: "red-team,c2,evasion,advanced",
      certBody: "Zero-Point Security",
      instructorId,
    },

    // --- Defensive Security / Blue Team ---
    {
      slug: "btl1-prep",
      title: "BTL1 — Blue Team Level 1 Certification",
      shortName: "BTL1",
      description: "Hands-on blue team training covering SOC operations, incident response, threat hunting, and log analysis.",
      longDescription: "BTL1 is a practical, hands-on blue team certification that covers the day-to-day operations of a SOC analyst. Includes phishing analysis, log analysis, SIEM operations, incident response, and threat intelligence.",
      category: "System Administration",
      level: "Beginner",
      durationHours: 60,
      price: 0,
      rating: 4.6,
      studentsCount: 2100,
      color: "cyan",
      tags: "soc,blue-team,incident-response,siem",
      certBody: "Security Blue Team",
      instructorId,
    },
    {
      slug: "cism-prep",
      title: "CISM — Certified Information Security Manager",
      shortName: "CISM",
      description: "Information security management, governance, risk management, and incident management for security leaders.",
      longDescription: "The CISM certification is designed for information security managers and aspiring CISOs. Covers information security governance, risk management, program development, and incident management.",
      category: "Security Management",
      level: "Advanced",
      durationHours: 70,
      price: 0,
      rating: 4.7,
      studentsCount: 1850,
      color: "amber",
      tags: "management,governance,risk,ciso",
      certBody: "ISACA",
      instructorId,
    },
    {
      slug: "cisa-prep",
      title: "CISA — Certified Information Systems Auditor",
      shortName: "CISA",
      description: "Information systems auditing, control, and security. Master IT audit and compliance frameworks.",
      longDescription: "The CISA certification is globally recognized for IT audit professionals. Covers auditing process, IT governance, systems acquisition, and information asset protection.",
      category: "Security Management",
      level: "Intermediate",
      durationHours: 65,
      price: 0,
      rating: 4.6,
      studentsCount: 1620,
      color: "amber",
      tags: "audit,compliance,governance,risk",
      certBody: "ISACA",
      instructorId,
    },

    // --- Cloud Security ---
    {
      slug: "aws-security",
      title: "AWS Certified Security — Specialty",
      shortName: "AWS-Sec",
      description: "Master AWS security services, identity management, data protection, and incident response in the cloud.",
      longDescription: "The AWS Security Specialty certification validates expertise in securing AWS environments. Covers IAM, VPC security, encryption, threat detection, and security automation.",
      category: "Cloud Security",
      level: "Advanced",
      durationHours: 80,
      price: 0,
      rating: 4.7,
      studentsCount: 1340,
      color: "cyan",
      tags: "aws,cloud,iam,encryption",
      certBody: "Amazon Web Services",
      instructorId,
    },
    {
      slug: "azure-security",
      title: "Microsoft Cyber Security Architect Expert",
      shortName: "AZ-500",
      description: "Azure security engineering, identity and access, platform protection, data security, and application security.",
      longDescription: "The Microsoft Cyber Security Architect Expert certification covers securing Azure environments including identity, platform, data, and application security with hands-on labs.",
      category: "Cloud Security",
      level: "Advanced",
      durationHours: 75,
      price: 0,
      rating: 4.5,
      studentsCount: 980,
      color: "cyan",
      tags: "azure,microsoft,cloud,identity",
      certBody: "Microsoft",
      instructorId,
    },
    {
      slug: "ccsk-prep",
      title: "CCSK — Certificate of Cloud Security Knowledge",
      shortName: "CCSK",
      description: "Foundation in cloud security. Covers CSA guidance, cloud computing concepts, and security best practices.",
      longDescription: "The CCSK is a vendor-neutral cloud security certification that provides a strong foundation in cloud security principles, architecture, and best practices based on the CSA guidance.",
      category: "Cloud Security",
      level: "Beginner",
      durationHours: 40,
      price: 0,
      rating: 4.4,
      studentsCount: 720,
      color: "cyan",
      tags: "cloud,vendor-neutral,foundation,csa",
      certBody: "Cloud Security Alliance",
      instructorId,
    },

    // --- Forensics & Incident Response ---
    {
      slug: "gcfa-prep",
      title: "GCFA — GIAC Certified Forensic Analyst",
      shortName: "GCFA",
      description: "Advanced digital forensics, incident response, and timeline analysis. Master memory and disk forensics.",
      longDescription: "The GCFA certification covers advanced incident response and digital forensics including memory forensics, disk forensics, timeline analysis, and investigating sophisticated intrusions.",
      category: "Forensics",
      level: "Advanced",
      durationHours: 85,
      price: 0,
      rating: 4.7,
      studentsCount: 640,
      color: "amber",
      tags: "forensics,incident-response,memory,disk",
      certBody: "GIAC",
      instructorId,
    },
    {
      slug: "gcih-prep",
      title: "GCIH — GIAC Certified Incident Handler",
      shortName: "GCIH",
      description: "Incident handling, attacker techniques, and containment strategies. Master the IR process end-to-end.",
      longDescription: "The GCIH certification focuses on incident handling and response. Covers common attack techniques, detection, containment, eradication, and recovery.",
      category: "Incident Response",
      level: "Intermediate",
      durationHours: 55,
      price: 0,
      rating: 4.6,
      studentsCount: 890,
      color: "amber",
      tags: "incident-response,handling,attacks,containment",
      certBody: "GIAC",
      instructorId,
    },

    // --- Web Application Security ---
    {
      slug: "ewptx-prep",
      title: "eWPTX — Web Application Penetration Testing eXtreme",
      shortName: "eWPTX",
      description: "Advanced web application penetration testing. Server-side and client-side exploitation, API security.",
      longDescription: "The eWPTX certification is an advanced web application penetration testing certification covering server-side exploits, client-side attacks, API security, and advanced bypass techniques.",
      category: "Web Security",
      level: "Advanced",
      durationHours: 70,
      price: 0,
      rating: 4.7,
      studentsCount: 540,
      color: "emerald",
      tags: "web,pentesting,api,advanced",
      certBody: "INE",
      instructorId,
    },
    {
      slug: "burp-certified",
      title: "Burp Suite Certified Practitioner",
      shortName: "BSCP",
      description: "Web vulnerability identification and exploitation using Burp Suite. Practical, hands-on certification.",
      longDescription: "The BSCP certification demonstrates practical ability to identify and exploit web vulnerabilities using Burp Suite Professional. Covers OWASP Top 10, business logic flaws, and advanced techniques.",
      category: "Web Security",
      level: "Intermediate",
      durationHours: 50,
      price: 0,
      rating: 4.6,
      studentsCount: 670,
      color: "emerald",
      tags: "burp,web,vulnerabilities,owasp",
      certBody: "PortSwigger",
      instructorId,
    },

    // --- Malware Analysis & Reverse Engineering ---
    {
      slug: "grem-prep",
      title: "GREM — GIAC Reverse Engineering Malware",
      shortName: "GREM",
      description: "Malware analysis and reverse engineering. Analyze malicious code, understand malware behavior, and develop detections.",
      longDescription: "The GREM certification covers reverse engineering malicious software including analyzing x86/x64 assembly, unpacking, analyzing obfuscated code, and understanding malware behavior.",
      category: "Malware Analysis",
      level: "Advanced",
      durationHours: 90,
      price: 0,
      rating: 4.7,
      studentsCount: 420,
      color: "violet",
      tags: "malware,reverse-engineering,assembly,analysis",
      certBody: "GIAC",
      instructorId,
    },
    {
      slug: "sep-prep",
      title: "Malware Analysis Professional — Reverse Engineering",
      shortName: "SEP",
      description: "Static and dynamic malware analysis. From basic behavior analysis to advanced code reverse engineering.",
      longDescription: "The SEP certification covers both static and dynamic malware analysis techniques. Includes sandboxing, debugging, disassembly, decompilation, and behavioral analysis.",
      category: "Malware Analysis",
      level: "Advanced",
      durationHours: 75,
      price: 0,
      rating: 4.5,
      studentsCount: 310,
      color: "violet",
      tags: "malware,static,dynamic,debugging",
      certBody: "SANS",
      instructorId,
    },

    // --- Network & IoT Security ---
    {
      slug: "gpen-prep",
      title: "GPEN — GIAC Certified Penetration Tester",
      shortName: "GPEN",
      description: "Professional penetration testing methodology, legal issues, and advanced exploitation techniques.",
      longDescription: "The GPEN certification covers penetration testing methodologies, legal compliance, reconnaissance, scanning, exploitation, and password attacks.",
      category: "Penetration Testing",
      level: "Intermediate",
      durationHours: 60,
      price: 0,
      rating: 4.6,
      studentsCount: 1100,
      color: "violet",
      tags: "pentesting,methodology,exploitation,passwords",
      certBody: "GIAC",
      instructorId,
    },
    {
      slug: "iot-security",
      title: "IoT Security Certification — Embedded Systems Security",
      shortName: "IoT-Sec",
      description: "Securing Internet of Things devices. Firmware analysis, hardware hacking, and IoT penetration testing.",
      longDescription: "This certification covers IoT security including firmware analysis, hardware hacking, UART/JTAG debugging, radio frequency analysis, and IoT penetration testing methodologies.",
      category: "Network Security",
      level: "Advanced",
      durationHours: 55,
      price: 0,
      rating: 4.4,
      studentsCount: 280,
      color: "cyan",
      tags: "iot,firmware,hardware,embedded",
      certBody: "GuardianX Academy",
      instructorId,
    },

    // --- AI Security ---
    {
      slug: "ai-security-fundamentals",
      title: "AI Security Fundamentals — Securing Machine Learning Systems",
      shortName: "AI-Sec",
      description: "Security of AI/ML systems. Adversarial attacks, model poisoning, data privacy, and securing ML pipelines.",
      longDescription: "This certification covers the security of artificial intelligence and machine learning systems. Topics include adversarial attacks, model inversion, data poisoning, differential privacy, and securing ML pipelines in production.",
      category: "Cloud Security",
      level: "Intermediate",
      durationHours: 45,
      price: 0,
      rating: 4.5,
      studentsCount: 450,
      color: "violet",
      tags: "ai,machine-learning,adversarial,privacy",
      certBody: "GuardianX Academy",
      instructorId,
    },

    // --- Governance & Compliance ---
    {
      slug: "iso-27001",
      title: "ISO 27001 — Information Security Management System",
      shortName: "ISO27001",
      description: "Implement and audit ISO 27001 ISMS. Risk assessment, controls, and certification audit preparation.",
      longDescription: "This certification covers the ISO 27001 standard for Information Security Management Systems (ISMS). Includes risk assessment, control implementation, audit preparation, and continuous improvement.",
      category: "Security Management",
      level: "Intermediate",
      durationHours: 50,
      price: 0,
      rating: 4.5,
      studentsCount: 890,
      color: "amber",
      tags: "iso,compliance,isms,risk",
      certBody: "ISO",
      instructorId,
    },
    {
      slug: "cissp-associate",
      title: "CISSP Associate — Information Security Fundamentals",
      shortName: "CISSP-A",
      description: "Start your CISSP journey. 8 domains of information security for aspiring security professionals.",
      longDescription: "The CISSP Associate path covers the 8 domains of the CISSP CBK including Security and Risk Management, Asset Security, Security Architecture, Communications Security, Identity and Access, Security Assessment, Security Operations, and Software Development Security.",
      category: "Security Management",
      level: "Intermediate",
      durationHours: 100,
      price: 0,
      rating: 4.7,
      studentsCount: 2200,
      color: "amber",
      tags: "cissp,management,domains,foundation",
      certBody: "ISC2",
      instructorId,
    },
    {
      slug: "soc2-implementation",
      title: "SOC 2 Implementation & Audit Preparation",
      shortName: "SOC2",
      description: "Implement SOC 2 controls, prepare for Type I and Type II audits, and build trust service frameworks.",
      longDescription: "This course covers SOC 2 implementation including the 5 trust service criteria (Security, Availability, Processing Integrity, Confidentiality, Privacy), control design, audit preparation, and continuous monitoring.",
      category: "Security Management",
      level: "Intermediate",
      durationHours: 40,
      price: 0,
      rating: 4.4,
      studentsCount: 380,
      color: "amber",
      tags: "soc2,audit,compliance,trust",
      certBody: "AICPA",
      instructorId,
    },
  ]

  for (const c of courses) {
    const existing = await db.course.findUnique({ where: { slug: c.slug } })
    if (existing) {
      await db.course.update({ where: { id: existing.id }, data: c })
      console.log(`  Updated: ${c.shortName} — ${c.title}`)
    } else {
      await db.course.create({ data: c })
      console.log(`  Created: ${c.shortName} — ${c.title}`)
    }
  }

  console.log(`\nTotal courses now: ${await db.course.count()}`)
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => db.$disconnect())
